"""Add configuration item

Revision ID: 0110110fa81e
Revises: ca50142ff511
Create Date: 2022-08-19 12:59:53.724585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0110110fa81e"
down_revision = "ca50142ff511"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("json_content", sa.Text(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("folder", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "date",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "Integer",
                "Float",
                "Date",
                "ShortString",
                "LongString",
                "Array",
                "Dictionnary",
                "Boolean",
                "File",
                name="configurationtypeenum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_config_name"), "config", ["name"], unique=True)
    op.create_index(op.f("ix_config_user_id"), "config", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_config_user_id"), table_name="config")
    op.drop_index(op.f("ix_config_name"), table_name="config")
    op.drop_table("config")
    # ### end Alembic commands ###
