"""Add event tags

Revision ID: 01d8429756a2
Revises: cd130569fb5a
Create Date: 2020-12-16 22:09:23.649937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d8429756a2'
down_revision = 'cd130569fb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GreenTransport', 'MountainProtection', 'Trip', 'Training', name='eventtagtypes'), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_table('event_tags')
    # ### end Alembic commands ###
