"""Add activity colum to uploaded_files

Revision ID: 0d576470d1ed
Revises: 58444ee06c99
Create Date: 2022-09-24 13:12:37.267189

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0d576470d1ed"
down_revision = "58444ee06c99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploaded_files") as batch_op:
        batch_op.add_column(sa.Column("activity_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            op.f("ix_uploaded_files_activity_id"), ["activity_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fkey_activity_id", "activity_types", ["activity_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploaded_files") as batch_op:
        batch_op.drop_constraint("fkey_activity_id", type_="foreignkey")
        batch_op.drop_index(op.f("ix_uploaded_files_activity_id"))
        batch_op.drop_column("activity_id")
    # ### end Alembic commands ###
