"""Add new badge types

Revision ID: 15f3ec45ac9b
Revises: 4a5c66ab7eaa
Create Date: 2023-11-04 10:33:35.176374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15f3ec45ac9b"
down_revision = "4a5c66ab7eaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.alter_column(
            "badge_id",
            existing_type_=sa.Enum("Benevole", name="badgeids"),
            type_=sa.Enum(
                "Benevole",
                "Initie",
                "Confirme",
                "InitiateurRecycle",
                "PSC1Recycle",
                name="badgeids",
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.alter_column(
            "badge_id",
            existing_type=sa.Enum(
                "Benevole",
                "Initie",
                "Confirme",
                "InitiateurRecycle",
                "PSC1Recycle",
                name="badgeids",
            ),
            type_=sa.Enum("Benevole", name="badgeids"),
            existing_nullable=False,
        )
