"""empty message

Revision ID: 20e75469b22b
Revises: aadaacde7f7e
Create Date: 2019-12-29 14:47:45.014246

"""
from alembic import op
import sqlalchemy as sa
from datetime import date

# revision identifiers, used by Alembic.
revision = '20e75469b22b'
down_revision = 'aadaacde7f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), server_default=str(date.today()), nullable=False))
    op.add_column('users', sa.Column('emergency_contact_name', sa.String(length=100), server_default='', nullable=False))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.String(length=20), server_default='', nullable=False))
    op.add_column('users', sa.Column('last_extranet_sync_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('license_expiry_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_users_license'), 'users', ['license'], unique=True)
    op.create_index(op.f('ix_users_mail'), 'users', ['mail'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mail'), table_name='users')
    op.drop_index(op.f('ix_users_license'), table_name='users')
    op.drop_column('users', 'license_expiry_date')
    op.drop_column('users', 'last_extranet_sync_time')
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'emergency_contact_name')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
