"""add equipments classes

Revision ID: 2a982c3401c1
Revises: bc252bdfe1a5
Create Date: 2021-09-28 21:09:56.739012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a982c3401c1'
down_revision = 'bc252bdfe1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'price')
    )
    op.create_table('equipment_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('type_equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_equipment_id'], ['equipment_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchaseDate', sa.DateTime(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('caution', sa.Float(), nullable=True),
    sa.Column('purchasePrice', sa.Float(), nullable=True),
    sa.Column('equipment_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_model_id'], ['equipment_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipments_purchaseDate'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_table('equipment_models')
    op.drop_table('equipment_types')
    # ### end Alembic commands ###
