"""Add attendance on event type

Revision ID: 2ae68816e937
Revises: 03efbbcc54de
Create Date: 2022-11-01 13:35:44.753226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ae68816e937"
down_revision = "03efbbcc54de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_types",
        sa.Column("attendance", sa.Boolean(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_types", "attendance")
    # ### end Alembic commands ###
