"""Add event parent/child relationship

Revision ID: 3529f70521c4
Revises: 92edd5d709ec
Create Date: 2021-06-03 22:48:46.443466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3529f70521c4"
down_revision = "92edd5d709ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events") as batch_op:
        batch_op.add_column(sa.Column("parent_event_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "parent_event_fkc", "events", ["parent_event_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registrations") as batch_op:
        batch_op.drop_constraint("parent_event_fkc", "events", type_="foreignkey")
    op.drop_column("events", "parent_event_id")
    # ### end Alembic commands ###
