"""Add refund time and metadata to payments table

Revision ID: 362909e71290
Revises: 88f73f88cb1b
Create Date: 2020-11-01 22:06:02.764092

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '362909e71290'
down_revision = '88f73f88cb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('refund_metadata', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('refund_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'refund_time')
    op.drop_column('payments', 'refund_metadata')
    # ### end Alembic commands ###
