"""Add Event.main_leader_id

Revision ID: 3ce1483e95a5
Revises: 8fcb27686a79
Create Date: 2020-04-03 19:59:02.268093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce1483e95a5'
down_revision = '8fcb27686a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('main_leader_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'events', 'users', ['main_leader_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'main_leader_id')
    # ### end Alembic commands ###
