"""add event type

Revision ID: 3d974e3ecddf
Revises: db73e93bf2b4
Create Date: 2021-10-30 13:56:06.573145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3d974e3ecddf"
down_revision = "db73e93bf2b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    event_types_table = op.create_table(
        "event_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("short", sa.String(length=256), nullable=False),
        sa.Column("requires_activity", sa.Boolean(), nullable=False),
        sa.Column("license_types", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.bulk_insert(
        event_types_table,
        [{"id": 1, "short": "tmp", "name": "tmp", "requires_activity": False}],
    )

    with op.batch_alter_table("events") as batch_op:
        batch_op.add_column(
            sa.Column(
                "event_type_id", sa.Integer(), nullable=False, server_default="1"
            ),
        )
        batch_op.create_foreign_key(
            "fkey_event_type", "event_types", ["event_type_id"], ["id"]
        )

    with op.batch_alter_table("activity_types") as batch_op:
        batch_op.add_column(sa.Column("deprecated", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_types") as batch_op:
        batch_op.drop_column("deprecated")

    with op.batch_alter_table("events") as batch_op:
        batch_op.drop_constraint("fkey_event_type", type_="foreignkey")
        batch_op.drop_column("event_type_id")

    op.drop_table("event_types")
    # ### end Alembic commands ###
