"""Wider processor length

Revision ID: 420c243a17f8
Revises: 1be67fc329bf
Create Date: 2026-09-23 20:07:09.248793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420c243a17f8'
down_revision = '1be67fc329bf'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('processor_token',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('processor_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('processor_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('processor_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
