"""Add badge condition and invert flag to user groups

Revision ID: 46e84942ea83
Revises: 68495dd11a7e
Create Date: 2025-06-29 14:15:49.487558

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46e84942ea83"
down_revision = "68495dd11a7e"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_badge_conditions",
        sa.Column(
            "badge_id",
            sa.Enum(
                "Benevole", "UnjustifiedAbsenceWarning", "Suspended", name="badgeids"
            ),
            nullable=True,
        ),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("invert", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["user_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("group_badge_conditions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_group_badge_conditions_group_id"), ["group_id"], unique=False
        )

    with op.batch_alter_table("group_event_conditions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("invert", sa.Boolean(), nullable=False, server_default="false")
        )

    with op.batch_alter_table("group_license_conditions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("invert", sa.Boolean(), nullable=False, server_default="false")
        )

    with op.batch_alter_table("group_role_conditions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("invert", sa.Boolean(), nullable=False, server_default="false")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_role_conditions", schema=None) as batch_op:
        batch_op.drop_column("invert")

    with op.batch_alter_table("group_license_conditions", schema=None) as batch_op:
        batch_op.drop_column("invert")

    with op.batch_alter_table("group_event_conditions", schema=None) as batch_op:
        batch_op.drop_column("invert")

    op.drop_table("group_badge_conditions")
    # ### end Alembic commands ###
