"""Add question models

Revision ID: 4a8c2871e259
Revises: 92a84e14f157
Create Date: 2023-09-23 10:13:07.684064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a8c2871e259"
down_revision = "4a5c66ab7eaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "SingleChoice",
                "MultipleChoices",
                "Numeric",
                "Text",
                "YesNo",
                name="questiontype",
            ),
            nullable=False,
        ),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("choices", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_questions_event_id"), ["event_id"], unique=False
        )

    op.create_table(
        "question_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_answers_question_id"), ["question_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("question_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_answers_question_id"))

    op.drop_table("question_answers")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_event_id"))

    op.drop_table("questions")
    # ### end Alembic commands ###
