"""Add auth0_id to User model

Revision ID: 4d25910e8aa5
Revises: dc23b36f42ef
Create Date: 2025-11-02 11:22:29.965587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d25910e8aa5'
down_revision = 'dc23b36f42ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add auth0_id column to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_auth0_id'), ['auth0_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove auth0_id column from users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_auth0_id'))
        batch_op.drop_column('auth0_id')

    # ### end Alembic commands ###
