"""add show_all_badges column to events table

Revision ID: 50b732cde535
Revises: dc23b36f42ef
Create Date: 2025-11-22 09:24:18.536527

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50b732cde535"
down_revision = "dc23b36f42ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "show_all_badges", sa.Boolean(), nullable=False, server_default="1"
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("show_all_badges")

    # ### end Alembic commands ###
