"""Add terms_title and terms_file to event_types

Revision ID: 527d9aca94fa
Revises: e40ba90ef64f
Create Date: 2022-01-09 13:13:36.055581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "527d9aca94fa"
down_revision = "e40ba90ef64f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_types") as batch_op:
        batch_op.add_column(
            sa.Column("terms_title", sa.String(length=256), nullable=True)
        )
        batch_op.add_column(
            sa.Column("terms_file", sa.String(length=256), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_types") as batch_op:
        batch_op.drop_column("terms_title")
        batch_op.drop_column("terms_file")
    # ### end Alembic commands ###
