"""Migration to camelcase

Revision ID: 58444ee06c99
Revises: 6b292b7e7d7b
Create Date: 2022-09-17 20:02:44.148276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58444ee06c99"
down_revision = "6b292b7e7d7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment_types") as batch_op:
        batch_op.alter_column(
            "pathImg", new_column_name="path_img", existing_type=sa.String(length=100)
        )

    with op.batch_alter_table("equipments") as batch_op:
        batch_op.alter_column(
            "purchaseDate",
            new_column_name="purchase_date",
            existing_type=sa.DateTime(),
        )
        batch_op.alter_column(
            "purchasePrice",
            new_column_name="purchase_price",
            existing_type=sa.Numeric(precision=8, scale=2),
        )


def downgrade():
    with op.batch_alter_table("equipment_types") as batch_op:
        batch_op.alter_column(
            "path_img", new_column_name="pathImg", existing_type=sa.String(length=100)
        )

    with op.batch_alter_table("equipments") as batch_op:
        batch_op.alter_column(
            "purchase_date",
            new_column_name="purchaseDate",
            existing_type=sa.DateTime(),
        )
        batch_op.alter_column(
            "purchase_price",
            new_column_name="purchasePrice",
            existing_type=sa.Numeric(precision=8, scale=2),
        )
    # ### end Alembic commands ###
