"""Migration to camelcase

Revision ID: 58444ee06c99
Revises: 0110110fa81e
Create Date: 2022-09-17 20:02:44.148276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58444ee06c99"
down_revision = "0110110fa81e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment_types") as batch_op:
        batch_op.alter_column("pathImg", new_column_name="path_img")

    with op.batch_alter_table("equipments") as batch_op:
        batch_op.alter_column("purchaseDate", new_column_name="purchase_date")
        batch_op.alter_column("purchasePrice", new_column_name="purchase_price")


def downgrade():
    with op.batch_alter_table("equipment_types") as batch_op:
        batch_op.alter_column("path_img", new_column_name="pathImg")

    with op.batch_alter_table("equipments") as batch_op:
        batch_op.alter_column("purchase_date", new_column_name="purchaseDate")
        batch_op.alter_column("purchase_price", new_column_name="purchasePrice")
    # ### end Alembic commands ###
