"""Add failed to conf tokens

Revision ID: 60ac67f0bc8a
Revises: aac7877cd693
Create Date: 2020-09-10 23:51:46.581156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ac67f0bc8a'
down_revision = 'aac7877cd693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("confirmation_token", schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed', sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('confirmation_token', 'failed')
    # ### end Alembic commands ###
