"""Add activity kind

Revision ID: 68495dd11a7e
Revises: 9590becba403
Create Date: 2025-06-16 20:55:41.473350

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68495dd11a7e"
down_revision = "9590becba403"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_types", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "kind",
                sa.Enum("Regular", "Service", name="activitykind"),
                nullable=False,
                server_default="Regular",
                info={"label": "Type d'activité"},
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("activity_types", schema=None) as batch_op:
        batch_op.drop_column("kind")

    # ### end Alembic commands ###
