"""link badge and registration models

Revision ID: 6bc0a1b73411
Revises: a86247f02e0a
Create Date: 2024-10-03 10:38:38.853825

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bc0a1b73411"
down_revision = "a86247f02e0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.add_column(sa.Column("registration_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_registration_id", "registrations", ["registration_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("registration_id")

    # ### end Alembic commands ###
