"""Add email to activity_types

Revision ID: 701afd89fc19
Revises: ca50142ff511
Create Date: 2022-08-19 14:11:26.320587

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "701afd89fc19"
down_revision = "03efbbcc54de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_types", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_types", schema=None) as batch_op:
        batch_op.drop_column("email")
    # ### end Alembic commands ###
