"""empty message

Revision ID: 706f5a8f8aea
Revises: e9202b0b2510
Create Date: 2020-01-03 22:41:22.216980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706f5a8f8aea'
down_revision = 'e9202b0b2510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_date'), 'event_logs', ['date'], unique=False)
    op.create_index(op.f('ix_event_logs_event_id'), 'event_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_logs_user_id'), 'event_logs', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():

    op.drop_index(op.f('ix_event_logs_user_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_date'), table_name='event_logs')
    op.drop_table('event_logs')
    # ### end Alembic commands ###
