"""add_reference_prefix

Revision ID: 70d17f3cd49f
Revises: 8bea958748e8
Create Date: 2022-02-16 16:30:12.525345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "70d17f3cd49f"
down_revision = "8bea958748e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment_types") as batch_op:
        batch_op.add_column(
            sa.Column("reference_prefix", sa.String(length=10), nullable=False),
        )
        batch_op.create_unique_constraint("UK_types_ref_prefix", ["reference_prefix"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment_types") as batch_op:
        batch_op.drop_constraint("UK_types_ref_prefix", type_="unique")
        batch_op.drop_column("reference_prefix")
    # ### end Alembic commands ###
