"""add ActivityStaff role

Revision ID: 75ca2437615d
Revises: 6bc0a1b73411
Create Date: 2024-12-16 18:30:59.457190

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75ca2437615d"
down_revision = "6bc0a1b73411"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            type_=sa.Enum(
                "Moderator",
                "Administrator",
                "President",
                "EventLeader",
                "ActivitySupervisor",
                "Technician",
                "Trainee",
                "Hotline",
                "Accountant",
                "Staff",
                "EquipmentManager",
                "EquipmentVolunteer",
                "ActivityStaff",
                name="roleids",
            ),
            existing_type_=sa.Enum(
                "Moderator",
                "Administrator",
                "President",
                "EventLeader",
                "ActivitySupervisor",
                "Technician",
                "Trainee",
                "Hotline",
                "Accountant",
                "Staff",
                "EquipmentManager",
                "EquipmentVolunteer",
                name="roleids",
            ),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            type_=sa.Enum(
                "Moderator",
                "Administrator",
                "President",
                "EventLeader",
                "ActivitySupervisor",
                "Technician",
                "Trainee",
                "Hotline",
                "Accountant",
                "Staff",
                "EquipmentManager",
                "EquipmentVolunteer",
                name="roleids",
            ),
            existing_type_=sa.Enum(
                "Moderator",
                "Administrator",
                "President",
                "EventLeader",
                "ActivitySupervisor",
                "Technician",
                "Trainee",
                "Hotline",
                "Accountant",
                "Staff",
                "EquipmentManager",
                "EquipmentVolunteer",
                "ActivityStaff",
                name="roleids",
            ),
        )
    # ### end Alembic commands ###
