"""add loxya synchronization columns

Tracks, for each user, the matching account on the Loxya equipment platform and
the last state pushed to it. See :py:mod:`collectives.utils.loxya_sync`.

Written by hand rather than kept as autogenerated: the autogenerated version
also carried unrelated drift between the models and a development database
(constraints, indices and enum types on config, events, payments, registrations
and retex), which has no place in a migration about Loxya.

Revision ID: 7babe0b3cfa2
Revises: b7c3e1d94f20
Create Date: 2026-09-22 22:34:08.809691

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7babe0b3cfa2"
down_revision = "b7c3e1d94f20"
branch_labels = None
depends_on = None

COLUMNS = (
    "loxya_beneficiary_id",
    "loxya_user_id",
    "loxya_active",
    "loxya_synced_at",
)
""" Names of the columns added by this migration. """

INDEX_NAME = "ix_users_loxya_beneficiary_id"
""" Index backing the lookup of a user from its Loxya beneficiary. """


def upgrade():
    """Adds the Loxya synchronization columns to the users table."""
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("loxya_beneficiary_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("loxya_user_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("loxya_active", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("loxya_synced_at", sa.DateTime(), nullable=True))
        batch_op.create_index(INDEX_NAME, ["loxya_beneficiary_id"], unique=False)


def downgrade():
    """Removes the Loxya synchronization columns.

    The link to the Loxya accounts is lost; those accounts are left untouched.
    They can be matched again from their ``reference`` field, which carries the
    Collectives user id.
    """
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(INDEX_NAME)
        for column in reversed(COLUMNS):
            batch_op.drop_column(column)
