"""Move manufacturer to model

Revision ID: 8bea958748e8
Revises: d9ae51d134ea
Create Date: 2022-01-28 16:03:47.915915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bea958748e8'
down_revision = 'd9ae51d134ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_models', sa.Column('manufacturer', sa.String(length=50), nullable=True))
    op.drop_column('equipments', 'manufacturer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipments', sa.Column('manufacturer', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('equipment_models', 'manufacturer')
    # ### end Alembic commands ###
