"""Add "processor_order_ref" field to Payment model

Revision ID: 8ddeb588a7a3
Revises: 564b1ed538b2
Create Date: 2020-07-29 18:48:27.407370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddeb588a7a3'
down_revision = '34af90a8159f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('processor_order_ref', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'processor_order_ref')
    # ### end Alembic commands ###
