"""Drop unique constraint on last reference field

Revision ID: 9226a31a5910
Revises: 1006bccb75da
Create Date: 2023-03-08 21:41:02.247843

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9226a31a5910"
down_revision = "1006bccb75da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment_types", schema=None) as batch_op:
        batch_op.drop_constraint("UK_last_reference", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment_types", schema=None) as batch_op:
        batch_op.create_unique_constraint("UK_last_reference", ["last_reference"])
    # ### end Alembic commands ###
