"""Remove email uniqueness


Revision ID: 96b5a190fc7c
Revises: 46e84942ea83
Create Date: 2025-09-28 10:42:00.729307

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96b5a190fc7c"
down_revision = "46e84942ea83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_mail")
        batch_op.create_index(batch_op.f("ix_users_mail"), ["mail"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_mail"))
        batch_op.create_index("ix_users_mail", ["mail"], unique=False)

    # ### end Alembic commands ###
