"""Add diploma

Revision ID: a47cbf29a577
Revises: 60ac67f0bc8a
Create Date: 2020-09-12 01:20:49.342174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47cbf29a577'
down_revision = 'b8e4572a4af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diploma_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=10), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diplomas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('obtention', sa.Date(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['diploma_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diplomas')
    op.drop_table('diploma_types')
    # ### end Alembic commands ###
