"""add badge creation time

Revision ID: a86247f02e0a
Revises: 01e5792cdfac
Create Date: 2024-09-02 10:27:36.900496

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a86247f02e0a"
down_revision = "01e5792cdfac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "creation_time",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():

    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.drop_column("creation_time")

    # ### end Alembic commands ###
