"""empty message

Revision ID: afe864919723
Revises: e9202b0b2510
Create Date: 2020-01-07 20:52:05.620125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe864919723'
down_revision = 'e9202b0b2510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('license_category', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'license_category')
    # ### end Alembic commands ###
