"""Remove flask-statistics

Revision ID: b738ba262419
Revises: c755ea630b55
Create Date: 2022-01-18 21:42:11.473168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b738ba262419"
down_revision = "c755ea630b55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_request_date", table_name="request")
    op.drop_index("ix_request_path", table_name="request")
    op.drop_table("request")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request",
        sa.Column("index", sa.INTEGER(), nullable=False),
        sa.Column("response_time", sa.FLOAT(), nullable=True),
        sa.Column("date", sa.DATETIME(), nullable=True),
        sa.Column("method", sa.TEXT(), nullable=True),
        sa.Column("size", sa.INTEGER(), nullable=True),
        sa.Column("status_code", sa.INTEGER(), nullable=True),
        sa.Column("path", sa.VARCHAR(length=128), nullable=True),
        sa.Column("user_agent", sa.TEXT(), nullable=True),
        sa.Column("remote_address", sa.TEXT(), nullable=True),
        sa.Column("exception", sa.TEXT(), nullable=True),
        sa.Column("referrer", sa.TEXT(), nullable=True),
        sa.Column("browser", sa.TEXT(), nullable=True),
        sa.Column("platform", sa.TEXT(), nullable=True),
        sa.Column("mimetype", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("index"),
    )
    op.create_index("ix_request_path", "request", ["path"], unique=False)
    op.create_index("ix_request_date", "request", ["date"], unique=False)
    # ### end Alembic commands ###
