"""Add 'max_uses' to payment item prices

Revision ID: bc252bdfe1a5
Revises: 3529f70521c4
Create Date: 2021-08-08 22:33:34.603795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc252bdfe1a5'
down_revision = '3529f70521c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_prices', sa.Column('max_uses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_prices', 'max_uses')
    # ### end Alembic commands ###
