"""Modifications on equipments models

Revision ID: bd8e76210a5d
Revises: bc252bdfe1a5
Create Date: 2021-10-20 14:03:03.090776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8e76210a5d'
down_revision = 'bc252bdfe1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('purchaseDate', sa.DateTime(), nullable=False),
    sa.Column('purchasePrice', sa.Float(), nullable=True),
    sa.Column('equipment_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_model_id'], ['equipment_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_purchaseDate'), 'equipments', ['purchaseDate'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['main_leader_id'], ['id'])
    op.drop_index('ix_payments_creditor_id', table_name='payments')
    op.create_index(op.f('ix_payments_buyer_id'), 'payments', ['buyer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_buyer_id'), table_name='payments')
    op.create_index('ix_payments_creditor_id', 'payments', ['buyer_id'], unique=False)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_equipments_purchaseDate'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_table('equipment_models')
    op.drop_table('equipment_types')
    # ### end Alembic commands ###
