"""Add custom badge levels

Revision ID: bf252f22e126
Revises: ff32e6834182
Create Date: 2025-10-11 11:48:43.657555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf252f22e126'
down_revision = 'ff32e6834182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_custom_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Enum('Benevole', 'UnjustifiedAbsenceWarning', 'Suspended', 'Practitioner', 'Skill', name='badgeids'), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbrev', sa.String(), nullable=False),
    sa.Column('default_validity', sa.Integer(), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('badge_custom_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badge_custom_levels_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_badge_custom_levels_badge_id'), ['badge_id'], unique=False)

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_badges_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_badges_registration_id'), ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_registration_id'))
        batch_op.drop_index(batch_op.f('ix_badges_level'))
        batch_op.drop_index(batch_op.f('ix_badges_badge_id'))

    with op.batch_alter_table('badge_custom_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badge_custom_levels_badge_id'))
        batch_op.drop_index(batch_op.f('ix_badge_custom_levels_activity_id'))

    op.drop_table('badge_custom_levels')
    # ### end Alembic commands ###
