"""add event visibility

Revision ID: c494eee43031
Revises: c556419fc6c2
Create Date: 2024-01-23 20:32:35.833475

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c494eee43031"
down_revision = "c556419fc6c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "visibility",
                sa.Enum("Public", "Private", name="eventvisibility"),
                nullable=False,
                server_default="Public",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("visibility")
    # ### end Alembic commands ###
