"""empty message

Revision ID: c4fd0b1c94ab
Revises: c60a90dd4554
Create Date: 2019-12-07 20:24:22.940683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fd0b1c94ab'
down_revision = 'c60a90dd4554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rendered_description', sa.Text(), nullable=True),
    sa.Column('shortdescription', sa.String(length=100), nullable=True),
    sa.Column('nbslots', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start', sa.DATETIME(), nullable=False),
    sa.Column('end', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('shortdescription', sa.VARCHAR(length=100), nullable=True),
    sa.Column('nbslots', sa.INTEGER(), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rendered_description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event')
    # ### end Alembic commands ###
