"""Add SecretFile to hot configuration

Revision ID: c556419fc6c2
Revises: 4a8c2871e259
Create Date: 2024-01-08 01:10:39.896152

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c556419fc6c2"
down_revision = "4a8c2871e259"
branch_labels = None
depends_on = None

before = sa.Enum(
    "Integer",
    "Float",
    "Date",
    "ShortString",
    "LongString",
    "Array",
    "Dictionnary",
    "Boolean",
    "File",
    name="configurationtypeenum",
)
after = sa.Enum(
    "Integer",
    "Float",
    "Date",
    "ShortString",
    "LongString",
    "Array",
    "Dictionnary",
    "Boolean",
    "File",
    "SecretFile",
    name="configurationtypeenum",
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=before,
            type_=after,
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("config", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=after,
            type_=before,
            nullable=False,
        )
