"""empty message

Revision ID: c60a90dd4554
Revises: c457a28f35a1
Create Date: 2019-12-01 21:29:40.104986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60a90dd4554'
down_revision = 'c457a28f35a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('rendered_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'rendered_description')
    # ### end Alembic commands ###
