""" Add leader-only prices

Revision ID: c755ea630b55
Revises: 527d9aca94fa
Create Date: 2022-01-16 13:25:14.861021

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c755ea630b55"
down_revision = "527d9aca94fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item_prices") as batch_op:
        batch_op.add_column(
            sa.Column("leader_only", sa.Boolean(), nullable=False, server_default="0")
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item_prices") as batch_op:
        batch_op.drop_column("leader_only")
    # ### end Alembic commands ###
