"""Add user followed activities

Revision ID: c84f9ec33732
Revises: 50b732cde535
Create Date: 2025-03-11 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c84f9ec33732"
down_revision = "50b732cde535"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_followed_activities",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_type_id", sa.Integer(), nullable=False),
        sa.Column("followed_at", sa.DateTime(), nullable=False),
        sa.Column("explicitly_unfollowed", sa.Boolean(), nullable=False, default=False),
        sa.Column("unfollowed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_type_id"],
            ["activity_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "activity_type_id"),
    )
    with op.batch_alter_table("user_followed_activities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_followed_activities_activity_type_id"),
            ["activity_type_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_followed_activities_user_id"), ["user_id"], unique=False
        )

    # Populate with existing data from registrations
    # This will auto-subscribe users to activities they've registered for
    op.execute(
        """
        INSERT INTO user_followed_activities (user_id, activity_type_id, followed_at, explicitly_unfollowed)
        SELECT DISTINCT r.user_id, eat.activity_id, datetime('now'), 0
        FROM registrations r
        JOIN events e ON r.event_id = e.id
        JOIN event_activity_types eat ON e.id = eat.event_id
        WHERE r.status IN (0, 1, 4)
        ON CONFLICT (user_id, activity_type_id) DO NOTHING
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_followed_activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_followed_activities_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_followed_activities_activity_type_id"))

    op.drop_table("user_followed_activities")
    # ### end Alembic commands ###
