"""Add waiting list

Revision ID: ca50142ff511
Revises: db73e93bf2b4
Create Date: 2021-10-26 22:17:42.020726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca50142ff511"
down_revision = "b738ba262419"
branch_labels = None
depends_on = None

before = sa.Enum(
    "Active",
    "Rejected",
    "PaymentPending",
    "SelfUnregistered",
    "JustifiedAbsentee",
    "UnJustifiedAbsentee",
)
after = sa.Enum(
    "Active",
    "Rejected",
    "PaymentPending",
    "SelfUnregistered",
    "JustifiedAbsentee",
    "UnJustifiedAbsentee",
    "Waiting",
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registrations") as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=before,
            type_=after,
            nullable=False,
        )
        before.name = "registrationstatus"
        after.name = "registrationstatus"
        batch_op.alter_column(
            "status",
            existing_type=before,
            type_=after,
            nullable=False,
        )

    with op.batch_alter_table("events") as batch_op:
        batch_op.add_column(
            sa.Column(
                "num_waiting_list", sa.Integer(), nullable=False, server_default="0"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registrations") as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=after,
            type_=before,
            nullable=False,
        )

    with op.batch_alter_table("events") as batch_op:
        batch_op.drop_column("num_waiting_list")
    # ### end Alembic commands ###
