"""Add field test for users

Revision ID: d71e68fc9505
Revises: 450db2068479
Create Date: 2020-01-16 21:52:02.405202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71e68fc9505'
down_revision = '450db2068479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_test', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_test')
    # ### end Alembic commands ###
