"""update badge_conditions enum

Revision ID: dc23b36f42ef
Revises: e2b8a6027968
Create Date: 2025-10-28 09:01:41.833678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc23b36f42ef'
down_revision = 'e2b8a6027968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("group_badge_conditions", schema=None) as batch_op:
        batch_op.alter_column(
            "badge_id",
            existing_type=sa.Enum(
                "Benevole", "UnjustifiedAbsenceWarning", "Suspended", name="badgeids"
            ),
            type_=sa.Enum(
                "Benevole", "UnjustifiedAbsenceWarning", "Suspended", "Practitioner", "Skill", name="badgeids"
            ),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("group_badge_conditions", schema=None) as batch_op:
        batch_op.alter_column(
            "badge_id",
            existing_type=sa.Enum(
                "Benevole", "UnjustifiedAbsenceWarning", "Suspended", "Practitioner", "Skill", name="badgeids"
            ),
            type_=sa.Enum(
                "Benevole", "UnjustifiedAbsenceWarning", "Suspended", name="badgeids"
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
