"""add retex table

Revision ID: dfadf58f0fac
Revises: 50b732cde535
Create Date: 2026-08-19 09:09:51.397738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfadf58f0fac'
down_revision = '50b732cde535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Normale', 'Annulee', 'Ecourtee', 'PresqueAccident', 'Accident', name='retexstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rendered_description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retex', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retex_event_id'), ['event_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retex', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retex_event_id'))

    op.drop_table('retex')
    # ### end Alembic commands ###
