"""Add level column to badge_custom_levels

Revision ID: e2b8a6027968
Revises: bf252f22e126
Create Date: 2025-10-27 20:54:28.936975

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2b8a6027968"
down_revision = "bf252f22e126"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badge_custom_levels", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("level", sa.Integer(), nullable=False, server_default="0")
        )

    op.execute("UPDATE badge_custom_levels SET level = id")

    with op.batch_alter_table("badge_custom_levels", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "_custom_level_uc", ["level", "badge_id", "activity_id"]
        )
        batch_op.create_index(
            batch_op.f("ix_badge_custom_levels_level"), ["level"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("badge_custom_levels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_badge_custom_levels_level"))
        batch_op.drop_constraint("_custom_level_uc", type_="unique")
        batch_op.drop_column("level")

    # ### end Alembic commands ###
