"""Add staff role

Revision ID: e40ba90ef64f
Revises: 3d974e3ecddf
Create Date: 2021-11-01 09:29:10.716161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e40ba90ef64f'
down_revision = '3d974e3ecddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            type_=sa.Enum(
                "Moderator",
                "Administrator",
                "President",
                "EventLeader",
                "ActivitySupervisor",
                "Technician",
                "Trainee",
                "Hotline",
                "Accountant",
                "Staff",
                name="roleids",
            ),
            existing_type_=sa.Enum(
                "Moderator",
                "Administrator",
                "President",
                "EventLeader",
                "ActivitySupervisor",
                "Technician",
                "Trainee",
                "Hotline",
                "Accountant",
                name="roleids",
            ),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            existing_type=sa.Enum(
                "Moderator",
                "Administrator",
                "President",
                "EventLeader",
                "ActivitySupervisor",
                "Technician",
                "Trainee",
                "Hotline",
                "Accountant",
                name="roleids",
            ),
            type_=sa.Enum(
                "Moderator",
                "Administrator",
                "President",
                "EventLeader",
                "ActivitySupervisor",
                "Technician",
                "Trainee",
                "Hotline",
                name="roleids",
            ),
        )
    # ### end Alembic commands ###
