"""Add date of signature for all users

Revision ID: e9f048fe1358
Revises: 8f698df8a06c
Create Date: 2020-03-04 21:31:16.554536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f048fe1358'
down_revision = '8f698df8a06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('legal_text_signature_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'legal_text_signature_date')
    # ### end Alembic commands ###
