"""Add last failed login date

Revision ID: e9fd4b35dee9
Revises: 19aba10b42ed
Create Date: 2020-02-02 15:20:19.576515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9fd4b35dee9'
down_revision = '19aba10b42ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_failed_login', sa.DateTime(), nullable=False, server_default='2000-01-01 00:00:00'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_failed_login')
    # ### end Alembic commands ###
