"""Add statistics

Revision ID: f559a516d597
Revises: 564b1ed538b2
Create Date: 2020-06-14 21:22:04.913415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f559a516d597'
down_revision = '564b1ed538b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('remote_address', sa.String(), nullable=True),
    sa.Column('exception', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
