"""Add competency level basges and group condition

Revision ID: ff32e6834182
Revises: 46e84942ea83
Create Date: 2025-10-04 20:12:21.419435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff32e6834182'
down_revision = '46e84942ea83'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_badge_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.alter_column(
            "badge_id",
            existing_type=sa.Enum(
                "Benevole", "UnjustifiedAbsenceWarning", "Suspended", name="badgeids"
            ),
            type_=sa.Enum(
                "Benevole", "UnjustifiedAbsenceWarning", "Suspended", "Practitioner", "Skill", name="badgeids"
            ),
            existing_nullable=False,
        )
        batch_op.add_column(sa.Column('grantor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fkey_grantor_id", 'users', ['grantor_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_badge_conditions', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.drop_constraint("fkey_grantor_id", type_='foreignkey')
        batch_op.drop_column('grantor_id')
        batch_op.alter_column(
            "badge_id",
            existing_type=sa.Enum(
                "Benevole", "UnjustifiedAbsenceWarning", "Suspended", "Practitioner", "Skill", name="badgeids"
            ),
            type_=sa.Enum(
                "Benevole", "UnjustifiedAbsenceWarning", "Suspended", name="badgeids"
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
