"""Module for profile related route

This modules contains the /profile Blueprint
"""

import hmac
import textwrap
from datetime import date
from io import BytesIO
from os.path import exists

from itsdangerous import BadSignature, SignatureExpired
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from flask_images import Images
from flask_login import current_user, logout_user
from markupsafe import Markup
from PIL import Image, ImageDraw, ImageFont

from collectives.forms import (
    ExtranetUserForm,
    LocalUserForm,
    NotificationPreferencesForm,
    csrf,
)
from collectives.forms.badge import CompetencyBadgeForm
from collectives.forms.user import DeleteUserForm
from collectives.models import (
    ActivityType,
    Badge,
    BadgeIds,
    Configuration,
    Event,
    EventType,
    Gender,
    Role,
    RoleIds,
    User,
    UserType,
    db,
)
from collectives.routes.auth import (
    EmailChangedError,
    InvalidLicenseError,
    get_changed_email_message,
    sync_user,
)
from collectives.utils.extranet import ExtranetError
from collectives.utils.misc import sanitize_file_name
from collectives.utils.profile_token import profile_token
from collectives.utils.time import current_time
from collectives.utils.url import slugify

images = Images()

blueprint = Blueprint("profile", __name__, url_prefix="/profile")


@blueprint.before_request
def before_request():
    """Protect all profile from unregistered access"""
    if request.endpoint in {
        "profile.notification_click",
        "profile.unsubscribe_notifications",
        "profile.unsubscribe_notifications_one_click",
    }:
        return None

    if not current_user.is_authenticated:
        return current_app.login_manager.unauthorized()

    if not current_user.has_signed_legal_text():
        flash("""Merci d'accepter les dernières mentions légales du site.""", "error")
        return redirect(url_for("root.legal"))

    return None


@blueprint.route("/user/<int:user_id>", methods=["GET"])
@blueprint.route("/user/<int:user_id>/from_event/<int:event_id>", methods=["GET"])
def show_user(user_id: int, event_id: int = 0):
    """Route to show detail of a regular user.

    :param int user_id: Primary key of the user.
    """

    user = db.session.get(User, user_id)
    if user is None:
        abort(404)

    practitioner_badge_form = None
    skill_badge_form = None
    notification_form = None

    if user.id != current_user.id:
        if not current_user.has_any_role():
            flash("Non autorisé", "error")
            return redirect(url_for("event.index"))

        if current_user.is_hotline() or current_user.is_supervisor():
            # Hotline and supervisors can access any profile freely
            pass
        elif current_user.can_create_events():
            # Leaders can access via either:
            # (a) a signed token generated by the user autocomplete/search flow
            #     (prevents ID enumeration when navigating to a profile)
            # (b) a valid event link (existing path for clicking a participant's name)
            token = request.args.get("token", "")
            has_valid_token = hmac.compare_digest(
                token, profile_token(current_user.id, user_id)
            )

            event: Event = db.session.get(Event, event_id) if event_id else None
            has_event_access = (
                event is not None
                and event.has_edit_rights(current_user)
                and event.is_registered(user)
            )

            if not has_valid_token and not has_event_access:
                flash("Non autorisé", "error")
                return redirect(url_for("event.index"))
        else:
            # Other roles need a link from an event to which the user is registered
            event = db.session.get(Event, event_id)

            if (
                event is None
                or not event.has_edit_rights(current_user)
                or not event.is_registered(user)
            ):
                flash("Non autorisé", "error")
                return redirect(url_for("event.index"))

        if not current_user.has_signed_ca():
            flash(
                """Vous devez signer la charte RGPD avant de pouvoir
                     accéder à des informations des utilisateurs""",
                "error",
            )
            return redirect(url_for("profile.confidentiality_agreement"))

        if current_user.is_leader() or current_user.can_manage_all_activities():
            practitioner_badge_form = CompetencyBadgeForm(
                badge_id=BadgeIds.Practitioner
            )
            skill_badge_form = CompetencyBadgeForm(badge_id=BadgeIds.Skill)

    if user.id == current_user.id:
        notification_form = NotificationPreferencesForm(current_user)
        notification_form.next.data = url_for("profile.show_user", user_id=user.id)

    return render_template(
        "profile/main.html",
        title="Profil adhérent",
        user=user,
        practitioner_badge_form=practitioner_badge_form,
        skill_badge_form=skill_badge_form,
        notification_form=notification_form,
        event_id=event_id,
    )


@blueprint.route("/organizer/<leader_id>", methods=["GET"])
def show_leader(leader_id):
    """Route to show leader details of a user.

    :param int leader_id: Primary key of the user.
    """
    user = User.query.filter_by(id=leader_id).first()

    # For now allow getting information about any user with roles
    # Limit to leaders of events the user is registered to?
    if user is None or not user.can_create_events():
        flash("Non autorisé", "error")
        return redirect(url_for("event.index"))

    if not current_user.can_see_leader_profile(user):
        flash("Non autorisé", "error")
        return redirect(url_for("event.index"))

    return render_template(
        "leader_profile.html",
        title="Profil adhérent",
        user=user,
    )


@blueprint.route("/user/edit", methods=["GET", "POST"])
def update_user():
    """Route to update current user information"""

    if current_user.type in (UserType.Local, UserType.UnverifiedLocal):
        form = LocalUserForm(obj=current_user)
    else:
        form = ExtranetUserForm(obj=current_user)

    if not form.validate_on_submit():
        form.password.data = None
        return render_template(
            "profile/edit_user.html",
            form=form,
            title="Profil adhérent",
            user=current_user,
        )

    user = current_user

    # Do not touch password if user does not want to change it
    if form.password.data == "":
        delattr(form, "password")

    form.populate_obj(user)

    # Save avatar into UploadSet
    if form.remove_avatar and form.remove_avatar.data:
        user.delete_avatar()
    if not user.save_avatar(form.avatar_file.data):
        flash("L'avatar téléchargé n'est pas dans un format d'image valide")

    db.session.add(user)
    db.session.commit()

    return redirect(url_for("profile.update_user"))


@blueprint.route("/user/notifications", methods=["GET", "POST"])
def update_notifications():
    """Route to update current user notification preferences."""

    form = NotificationPreferencesForm(current_user)
    next_url = form.next.data

    if form.validate_on_submit():
        was_enabled = current_user.new_event_notification_enabled
        current_user.new_event_notification_enabled = (
            form.new_event_notification_enabled.data
        )
        current_user.new_event_notification_frequency = (
            form.new_event_notification_frequency.data
        )

        selected_event_types = (
            EventType.query.filter(EventType.id.in_(form.event_type_ids.data)).all()
            if form.event_type_ids.data
            else []
        )
        normalized_activity_type_ids = form.normalized_activity_type_ids()
        selected_activity_types = (
            ActivityType.query.filter(
                ActivityType.id.in_(normalized_activity_type_ids)
            ).all()
            if normalized_activity_type_ids
            else []
        )

        current_user.notified_event_types = selected_event_types
        current_user.notified_activity_types = selected_activity_types
        current_user.set_notification_weekday_list(form.weekdays.data)
        if current_user.new_event_notification_enabled and not was_enabled:
            current_user.last_new_event_notification_sent_at = current_time()
            current_user.new_event_notification_warning_sent_at = None
        if not current_user.new_event_notification_enabled:
            current_user.new_event_notification_warning_sent_at = None

        db.session.add(current_user)
        db.session.commit()

        flash("Préférences de notification mises à jour", "success")
        if next_url and next_url.startswith("/") and not next_url.startswith("//"):
            return redirect(next_url)
        return redirect(url_for("profile.update_notifications"))

    if next_url == url_for("profile.show_user", user_id=current_user.id):
        return render_template(
            "profile/main.html",
            title="Profil adhérent",
            user=current_user,
            practitioner_badge_form=None,
            skill_badge_form=None,
            notification_form=form,
            event_id=0,
        )

    return render_template(
        "profile/notification_preferences.html",
        notification_form=form,
        title="Mes notifications",
        description=(
            "Choisissez les types de collectives à surveiller. "
            "Les notifications sont envoyées sous forme de récapitulatif quotidien "
            "ou hebdomadaire si la collective correspond aux filtres."
        ),
    )


@blueprint.route("/user/notifications/click/<token>", methods=["GET"])
def notification_click(token: str):
    """Track clicks from digest emails and redirect to the target event."""
    serializer = current_app.extensions["new_event_notification_serializer"]
    try:
        payload = serializer.loads(
            token,
            max_age=current_app.config["NEW_EVENT_NOTIFICATION_CLICK_TOKEN_MAX_AGE"],
        )
    except SignatureExpired:
        flash("Lien de notification expiré", "error")
        return redirect(url_for("root.index"))
    except BadSignature:
        flash("Lien de notification invalide", "error")
        return redirect(url_for("root.index"))

    if payload.get("action") != "click":
        flash("Lien de notification invalide", "error")
        return redirect(url_for("root.index"))

    user = db.session.get(User, payload.get("user_id"))
    event = db.session.get(Event, payload.get("event_id"))
    if user is None or event is None:
        flash("Lien de notification invalide", "error")
        return redirect(url_for("root.index"))

    user.last_new_event_notification_clicked_at = current_time()
    user.new_event_notification_warning_sent_at = None
    db.session.add(user)
    db.session.commit()

    return redirect(
        url_for("event.view_event", event_id=event.id, name=slugify(event.title))
    )


@blueprint.route("/user/notifications/unsubscribe/<token>", methods=["GET"])
@blueprint.route("/user/notifications/unsubscribe/<token>", methods=["POST"])
def unsubscribe_notifications(token: str):
    """Display or apply one-click unsubscribe for notification digests."""
    user = _load_unsubscribe_user_from_token(token)
    if user is None:
        return redirect(url_for("root.index"))

    if request.method == "GET":
        return render_template(
            "profile/unsubscribe_notifications.html",
            title="Confirmer le désabonnement",
            description=(
                "Cette page confirme l'arrêt des notifications de nouvelles "
                "collectives pour ce compte."
            ),
            token=token,
        )

    user.new_event_notification_enabled = False
    user.new_event_notification_warning_sent_at = None
    db.session.add(user)
    db.session.commit()
    flash("Les notifications de nouvelles collectives ont été désactivées.", "success")
    if current_user.is_authenticated and current_user.id == user.id:
        return redirect(url_for("profile.update_notifications"))
    return redirect(
        url_for("auth.login", next=url_for("profile.update_notifications"))
    )


def _load_unsubscribe_user_from_token(token: str):
    """Resolve the signed unsubscribe token into a user."""
    serializer = current_app.extensions["new_event_notification_serializer"]
    try:
        payload = serializer.loads(
            token,
            max_age=current_app.config[
                "NEW_EVENT_NOTIFICATION_UNSUBSCRIBE_TOKEN_MAX_AGE"
            ],
        )
    except SignatureExpired:
        flash("Lien de désabonnement expiré", "error")
        return None
    except BadSignature:
        flash("Lien de désabonnement invalide", "error")
        return None

    if payload.get("action") != "unsubscribe":
        flash("Lien de désabonnement invalide", "error")
        return None

    user = db.session.get(User, payload.get("user_id"))
    if user is None:
        flash("Lien de désabonnement invalide", "error")
        return None
    return user


@blueprint.route(
    "/user/notifications/unsubscribe/one-click/<token>", methods=["POST"]
)
@csrf.exempt
def unsubscribe_notifications_one_click(token: str):
    """RFC 8058 one-click unsubscribe endpoint for email clients."""
    user = _load_unsubscribe_user_from_token(token)
    if user is None:
        return "", 400
    if request.form.get("List-Unsubscribe") != "One-Click":
        return "", 400
    user.new_event_notification_enabled = False
    user.new_event_notification_warning_sent_at = None
    db.session.add(user)
    db.session.commit()
    return "", 204


@blueprint.route("/user/force_sync", methods=["POST"], defaults={"user_id": None})
@blueprint.route("/user/<int:user_id>/force_sync", methods=["POST"])
def force_user_sync(user_id):
    """Route to force user synchronisation with extranet"""
    if user_id is None:
        user = current_user
    else:
        user = db.session.get(User, user_id)

    if user is None:
        flash("Utilisateur inconnu", "error")
        return redirect(url_for("root.index"))

    if user.id != current_user.id:
        if not current_user.is_hotline():
            flash("Non autorisé", "error")
            return redirect(url_for("profile.show_user", user_id=user.id))

        if not current_user.has_signed_ca():
            flash(
                """Vous devez signer la charte RGPD avant de pouvoir
                    accéder à des informations des utilisateurs""",
                "error",
            )
            return redirect(url_for("profile.show_user", user_id=user.id))

    try:
        sync_user(user, force=True)
    except InvalidLicenseError:
        if user.id == current_user.id:
            flash(
                f'Votre numéro de licence "{user.license}" n\'est pas ou plus valide '
                "dans la base fédérale. Si un nouveau numéro de licence vous a été attribué, "
                "vous pouvez utiliser le formulaire de récupération ci-dessous pour "
                "le ré-associer avec compte",
                "error",
            )
            logout_user()
            return redirect(url_for("auth.recover"))

        flash(
            f'Le numéro de licence "{user.license}" n\'est pas ou plus valide.',
            "error",
        )
    except EmailChangedError as err:
        flash(Markup(get_changed_email_message(err.new_email)), "error")
    except ExtranetError:
        flash(
            "Impossible de se connecter à l'extranet, veuillez réessayer ultérieurement",
            "error",
        )

    return redirect(url_for("profile.show_user", user_id=user.id))


@blueprint.route("/user/confidentiality", methods=["GET", "POST"])
def confidentiality_agreement():
    """Route to show confidentiality agreement."""
    if (
        request.method == "POST"
        and current_user.confidentiality_agreement_signature_date is None
    ):
        current_user.confidentiality_agreement_signature_date = current_time()
        db.session.add(current_user)
        db.session.commit()
        flash("Merci d'avoir signé la charte RGPD", "success")

    return render_template("confidentiality_agreement.html", title="Charte RGPD")


@blueprint.route("/my_payments", methods=["GET"])
def my_payments():
    """Route to show payments associated to the current user"""
    return render_template("profile/my_payments.html", title="Mes paiements")


@blueprint.route("/user/volunteer/cert")
def volunteer_certificate():
    """Route to show the volunteer cert of a regular user."""
    if not Configuration.VOLUNTEER_CERT_IMAGE or not exists(
        Configuration.VOLUNTEER_CERT_IMAGE
    ):
        # No president signature
        flash(
            "Impossible de générer l'attestation bénévole. "
            "La fonctionnalité est désactivée",
            "error",
        )
        return redirect(url_for("profile.show_user", user_id=current_user.id))
    if (
        not current_user.has_a_valid_benevole_badge()
        and not current_user.has_any_role()
    ):
        flash("Non autorisé", "error")
        return redirect(url_for("event.index"))

    president = User.query.filter(
        User.roles.any(Role.role_id == RoleIds.President)
    ).first()
    if not president:
        # No president in roles table
        flash(
            """Impossible de générer l'attestation bénévole.
                Le club n'a pas de président, merci de contacter le support.""",
            "error",
        )
        return redirect(url_for("profile.show_user", user_id=current_user.id))

    # usefull variables
    font_file = "collectives/static/fonts/DINWeb.woff"
    font = ImageFont.truetype(font_file, 50)
    black = (0, 0, 0)

    # Setup rotated watermark
    template = Image.open(Configuration.VOLUNTEER_CERT_IMAGE)
    size = template.size
    width = template.size[0]
    image = Image.new("RGBA", (int(size[0] * 1.2), int(size[1] * 1.1)), "#ffffff")
    watermark_text = f"{current_user.full_name()} - {current_user.license} - " * 6
    watermark_text = [" " * 20 * (i % 4) + watermark_text + "\n" for i in range(75)]
    watermark_text = "\n".join(watermark_text)
    ImageDraw.Draw(image).multiline_text(
        (-1000, 0),
        watermark_text,
        "#00000018",
        font=font,
        spacing=-10,
    )
    image = image.rotate(10)
    image = image.crop((size[0] * 0.1, size[1] * 0.05, size[0] * 1.1, size[1] * 1.05))
    image.paste(template, (0, 0), template)

    # Add Header text
    ImageDraw.Draw(image).multiline_text(
        (width / 2, 500),
        f"Attestation de fonction Bénévole\nau {Configuration.CLUB_NAME}",
        black,
        font=ImageFont.truetype(font_file, 100),
        anchor="ms",
        align="center",
    )

    # Add Main text
    conjugate = "e" if current_user.gender == Gender.Woman else ""
    club_name = Configuration.CLUB_NAME
    if current_user.license_expiry_date:
        expiry = current_user.license_expiry_date.year
    elif current_user.type == UserType.Test:
        expiry = 1789  # Default year if user is a test user
    else:
        flash("""Erreur de date de license. Contactez le support.""", "error")
        return redirect(url_for("profile.show_user", user_id=current_user.id))

    text = (
        f"Je sous-signé, {president.full_name()}, président du {club_name} "
        "certifie que:\n\n"
        f"                       {current_user.form_of_address()} "
        f"{current_user.full_name()}, né{conjugate} le "
        f"{current_user.date_of_birth.strftime('%d/%m/%Y')}, \n\n"
        f"est licencié{conjugate} au {club_name} sous le numéro d'adhérent "
        f"{current_user.license}, est membre de la FFCAM, la Fédération "
        "Française des Clubs Alpins et de Montagne, est à jour de cotisation "
        f"pour l'année en cours, du 1er septembre {expiry - 1} au 30 septembre "
        f"{expiry}, et est Bénévole reconnu{conjugate} au sein de notre "
        "association.\n\n"
        f"Nom et adresse de la structure:\n{Configuration.CLUB_IDENTITY}\n"
        "\n\n"
        "Pour toute question ou réclamation concernant l'attestation: "
        f"{Configuration.CONTACT_EMAIL}\n\n"
        "Ces informations sont certifiées conformes."
    )

    ImageDraw.Draw(image).multiline_text(
        (width / 2, 900),
        "\n".join([textwrap.fill(line, width=80) for line in text.split("\n")]),
        black,
        font=font,
        anchor="ms",
        spacing=45,
    )

    ImageDraw.Draw(image).multiline_text(
        (1580, 2550),
        f"Fait le {date.today().strftime('%d/%m/%Y')}\n"
        "Cachet et signature du président",
        black,
        font=font,
        spacing=10,
    )

    no_alpha = Image.new("RGB", image.size, (255, 255, 255))
    no_alpha.paste(image, (0, 0), image)
    out = BytesIO()
    no_alpha.save(out, "PDF")
    out.seek(0)

    club_name = sanitize_file_name(Configuration.CLUB_NAME)

    # Show file to user
    return send_file(
        out,
        mimetype="application/pdf",
        download_name=f"Attestation Benevole {club_name}.pdf",
        as_attachment=True,
    )


@blueprint.route("/delete", methods=["GET", "POST"], defaults={"user_id": None})
@blueprint.route("/<int:user_id>/delete", methods=["GET", "POST"])
def delete_user(user_id: int):
    """Route to delete an user."""

    if user_id is None:
        user_id = current_user.id

    if user_id == current_user.id:
        if current_user.is_admin():
            flash(
                "En tant qu'administateur, vous ne pouvez pas supprimer votre propre compte",
                "error",
            )
            return redirect(url_for(".show_user", user_id=user_id))
    elif not current_user.is_hotline():
        flash("Opération interdite", "error")
        return redirect(url_for(".show_user", user_id=user_id))

    user: User = db.session.get(User, user_id)
    if user is None:
        flash("Utilisateur invalide", "error")
        return redirect(url_for(".show_user", user_id=user_id))

    form = DeleteUserForm(user)

    if form.validate_on_submit():
        old_name = user.full_name()

        # Anonymize account
        # Keep only gender and license category for statistics
        user.enabled = False
        user.first_name = "Compte"
        user.last_name = "Supprimé"
        user.license = str(user_id)
        user.mail = f"{user.license}@localhost"
        user.date_of_birth = date(user.date_of_birth.year, 1, 1)
        user.password = ""
        user.phone = ""
        user.emergency_contact_name = ""
        user.emergency_contact_phone = ""
        user.roles.clear()
        user.badges.clear()
        user.notified_event_types.clear()
        user.notified_activity_types.clear()
        user.new_event_notification_enabled = False
        user.new_event_notification_weekdays = None
        user.delete_avatar()

        db.session.add(user)
        db.session.commit()

        flash(f"Le compte de {old_name} a bien été supprimé")

        if user_id == current_user.id:
            logout_user()
            return redirect(url_for("auth.login"))

        return redirect(url_for("administration.administration"))

    return render_template(
        "profile/delete_user.html",
        title="Suppression d'un compte",
        user=user,
        form=form,
    )


@blueprint.route(
    "/user/<int:user_id>/set_competency_badge/<int:badge_id>/from_event/<int:event_id>",
    methods=["POST"],
)
def set_competency_badge(user_id: int, badge_id: int, event_id: int):
    """Route for leaders to add/update a competency badge to a user."""
    user = db.session.get(User, user_id)
    if user is None:
        flash("Utilisateur invalide", "error")
        return redirect(url_for(".show_user", user_id=user_id, event_id=event_id))

    if not current_user.is_leader() and not current_user.can_manage_all_activities():
        flash("Non autorisé", "error")
        return redirect(url_for(".show_user", user_id=user_id, event_id=event_id))

    badge_id = BadgeIds(badge_id)

    form = CompetencyBadgeForm(badge_id=badge_id)

    if form.validate_on_submit():
        level = form.level.data
        if level:
            level_desc = badge_id.levels()[level]

        if badge_id == BadgeIds.Practitioner:
            activity_id = form.activity_id.data
        else:
            activity_id = level_desc.activity_id

        if (
            not current_user.can_manage_all_activities()
            and activity_id is not None
            and not current_user.can_lead_activity(ActivityType.get(activity_id))
        ):
            flash(
                "Vous ne pouvez pas définir un niveau de pratique pour une activité "
                "dont vous n'êtes pas encadrant(e)",
                "error",
            )
            return redirect(url_for(".show_user", user_id=user_id, event_id=event_id))

        badge = user.get_most_relevant_competency_badge(
            badge_id=badge_id, activity_id=activity_id, level=level, valid_only=False
        )

        if not level:
            # Remove badge if level is 0
            if badge is not None:
                db.session.delete(badge)
        else:
            if badge is None:
                badge = Badge(
                    badge_id=badge_id,
                    user_id=user.id,
                    activity_id=activity_id,
                )

            badge.level = form.level.data
            badge.expiration_date = level_desc.expiry_date()
            badge.grantor_id = current_user.id
            db.session.add(badge)

        db.session.commit()
        flash(f"Badge {badge_id.display_name()} mis à jour", "success")

    return redirect(url_for(".show_user", user_id=user_id, event_id=event_id))


@blueprint.route("/search", methods=["GET"])
def search_user():
    """Route for leaders to search for users by name.

    Accessible to users who can create events (leaders, supervisors, etc.).
    Requires the RGPD confidentiality agreement to be signed.
    """
    if not Configuration.USER_SEARCH_ENABLED:
        abort(404)

    if not current_user.can_create_events():
        flash("Non autorisé", "error")
        return redirect(url_for("event.index"))

    if not current_user.has_signed_ca():
        flash(
            """Vous devez signer la charte RGPD avant de pouvoir
                 accéder à des informations des utilisateurs""",
            "error",
        )
        return redirect(url_for("profile.confidentiality_agreement"))

    return render_template("profile/search.html", title="Recherche d'adhérent")
